server:
  port: 0
spring:
  application:
    name: hello-service
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int(1000,9999)}
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
